### PR TITLE
Adds 'admin surveys' to user admin modal.

### PR DESCRIPTION
**Pull request by jmwohl**
@vr2262 
Also a couple tests for Settings... one fails now, not sure the best way to fix it (see comment in test) Thoughts?

### CODE REVIEW

**Comment by vr2262** [comment]
@jmwohl looking into it...

**Comment by vr2262** [comment]
@jmwohl 
What's the issue with simply checking that the API token field is not empty? Seems good enough to me...

**Comment by jmwohl** [comment]
Yeah, that check should be sufficient, I just couldn't get it to work... it
makes an ajax call, so it needs to wait until it populates, and I wasn't
sure how to do that.

On Thu, Oct 1, 2015 at 12:44 PM, Viktor Roytman <notifications@github.com>
wrote:

> @jmwohl <https://github.com/jmwohl>
> What's the issue with simply checking that the API token field is not
> empty? Seems good enough to me...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEL-Columbia/dokomoforms/pull/168#issuecomment-144783262>
> .
>



-- 
Jonathan Wohl
(608)-772-9645

**Comment by vr2262** [comment]
Oh... eh, a `sleep` should be fine...

**Comment by vr2262** [comment]
Woah... turns out this test found a bug (sort of...).
By default `xvfb-run` creates a window with mysterious dimensions. Here's the screenshot:

bad

The user dropdown isn't visible, which means it's not clickable.

At this point we can either make a CSS change (the "right" thing to do) or pass an argument to `xvfb-run` so that it has sensible window dimensions.

**Comment by vr2262** [comment]
@jmwohl 
This display issue is the only problem with the tests now.

**Comment by jmwohl** [comment]
It would be quite a hassle to make the admin area responsive, so I'd vote
for setting a bigger screen size for the tests for now if that's easy. If
we want to support smaller screens we can make it a story.

On Oct 1, 2015, at 2:06 PM, Viktor Roytman <notifications@github.com> wrote:

@jmwohl <https://github.com/jmwohl>
This display issue is the only problem with the tests now.

—
Reply to this email directly or view it on GitHub
<https://github.com/SEL-Columbia/dokomoforms/pull/168#issuecomment-144803192>
.

**Comment by vr2262** [comment]
In the long run it would be nice to be able to view survey stats on your phone, but it is a lot of work. Please add a story for it.

For now, I'll make the `xvfb` change.

**Comment by vr2262** [comment]
OK. Assuming the test passes on Travis, this pull request should be good to go.

**Pull request merged**
