### PR TITLE
Dockomoforms compose

### PR DESCRIPTION
**Pull request by myf**
dokomo-compose up works,
having python to handle db issues
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/SEL-Columbia/dokomoforms/pull/139%23issuecomment-98137459%22%2C%20%22https%3A//github.com/SEL-Columbia/dokomoforms/commit/55b149b804c3828d137dc22ce61452f0e0275ac2%23commitcomment-11001436%22%2C%20%22https%3A//github.com/SEL-Columbia/dokomoforms/pull/139%23issuecomment-98149727%22%2C%20%22https%3A//github.com/SEL-Columbia/dokomoforms/pull/139%23issuecomment-99194103%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/SEL-Columbia/dokomoforms/pull/139%23issuecomment-98137459%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Can%20you%20move%20the%20docker-specific%20stuff%20into%20its%20own%20folder%3F%22%2C%20%22created_at%22%3A%20%222015-05-01T13%3A42%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2337403%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/vr2262%22%7D%7D%2C%20%7B%22body%22%3A%20%22Cannot%2C%20they%20need%20to%20be%20in%20the%20main%20folder%20to%20build%5CnOn%20May%201%2C%202015%209%3A42%20AM%2C%20%5C%22Viktor%20Roytman%5C%22%20%3Cnotifications%40github.com%3E%20wrote%3A%5Cn%5Cn%3E%20Can%20you%20move%20the%20docker-specific%20stuff%20into%20its%20own%20folder%3F%5Cn%3E%5Cn%3E%20%5Cu2014%5Cn%3E%20Reply%20to%20this%20email%20directly%20or%20view%20it%20on%20GitHub%5Cn%3E%20%3Chttps%3A//github.com/SEL-Columbia/dokomoforms/pull/139%23issuecomment-98137459%3E%5Cn%3E%20.%5Cn%3E%5Cn%22%2C%20%22created_at%22%3A%20%222015-05-01T15%3A02%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/694376%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/myf%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%27m%20accepting%20the%20pull%20request...%20we%20need%20to%20clean%20up%20the%20Vagrant/Docker%20situation%20somewhere%20down%20the%20line...%22%2C%20%22created_at%22%3A%20%222015-05-05T19%3A24%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2337403%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/vr2262%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22Commit%2055b149b804c3828d137dc22ce61452f0e0275ac2%20docker-compose.yml%207%2010%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/SEL-Columbia/dokomoforms/commit/55b149b804c3828d137dc22ce61452f0e0275ac2%23commitcomment-11001436%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Does%20someone%20these%20Docker%20settings%20just%20change%20the%20password%20here%20and%20in%20%60local_settings.py%60%3F%22%2C%20%22created_at%22%3A%20%222015-05-01T13%3A47%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2337403%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/vr2262%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20docker-compose.yml%3AL10%20%2855b149b%29%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/SEL-Columbia/dokomoforms/pull/139#issuecomment-98137459'>General Comment</a></b>
- <a href='https://github.com/vr2262'></a> Can you move the docker-specific stuff into its own folder?
- <a href='https://github.com/myf'></a> Cannot, they need to be in the main folder to build
On May 1, 2015 9:42 AM, "Viktor Roytman" <notifications@github.com> wrote:
> Can you move the docker-specific stuff into its own folder?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEL-Columbia/dokomoforms/pull/139#issuecomment-98137459>
> .
>
- <a href='https://github.com/vr2262'></a> I'm accepting the pull request... we need to clean up the Vagrant/Docker situation somewhere down the line...
- [ ] <a href='#crh-comment-Commit 55b149b804c3828d137dc22ce61452f0e0275ac2 docker-compose.yml 7 10'></a> &nbsp;<b><a href='https://github.com/SEL-Columbia/dokomoforms/commit/55b149b804c3828d137dc22ce61452f0e0275ac2#commitcomment-11001436'>File: docker-compose.yml:L10 (55b149b)</a></b>
- <a href='https://github.com/vr2262'></a> Does someone these Docker settings just change the password here and in `local_settings.py`?

<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/139?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/SEL-Columbia/dokomoforms/pull/139?approve=1'></a>&nbsp;<a href='https://github.com/SEL-Columbia/dokomoforms/pull/139'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by vr2262** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/SEL-Columbia/dokomoforms/pull/139'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by vr2262** [comment]
Can you move the docker-specific stuff into its own folder?

**Comment by myf** [comment]
Cannot, they need to be in the main folder to build

**Comment by vr2262** [comment]
I'm accepting the pull request... we need to clean up the Vagrant/Docker situation somewhere down the line...

**Pull request merged**
